# Generated by Django 5.0.6 on 2024-06-29 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('animal_present', models.BooleanField(default=False)),
                ('animal_type', models.CharField(max_length=100)),
                ('image_file', models.ImageField(upload_to='images/')),
                ('image_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('animal_present', models.BooleanField(default=None, null=True)),
                ('animal_type', models.CharField(max_length=100)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('session_num', models.IntegerField(default=0)),
                ('ap_correct', models.BooleanField(default=None, null=True)),
                ('at_correct', models.BooleanField(default=None, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='myapp.image')),
            ],
        ),
    ]
