# Generated by Django 5.0.6 on 2024-07-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_image_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='session_num',
            field=models.CharField(default='', max_length=255),
        ),
    ]
